# Generated by Django 3.0.8 on 2020-07-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('author', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
